### ISSUE TITLE
v 0.15.4 from vs gallery locks up vs 2015.1+ when ever I text edit a paket.dependency file

### ISSUE THREAD

**Issue by sillyotter** [fsprojects/Paket.VisualStudio#106] opened 2016-03-04 14:40 UTC
Just received an update to Paket.Visualstudio through the extension update service.  0.15.4.  Every time I try to edit a paket.dependency file, vs locks up and I have to kill the process.  

Not sure what information would help diagnose this.  Win10EE, VS2015.1 with all updates installed as of this morning.

**Comment by forki** [comment] 2016-03-04 14:44
shit. It's probably related to https://github.com/fsprojects/Paket.VisualStudio/issues/105

can you describe what I have to do to reproduce?

**Comment by forki** [comment] 2016-03-04 14:48
looks like I can reproduce

**Comment by forki** [comment] 2016-03-04 14:52
fixed in 0.15.5

**Closed as completed** 2016-03-04 14:52 UTC
Labels: bug

**Comment by sillyotter** [comment] 2016-03-04 14:58
That fixed it.  Thanks
