### ISSUE TITLE
Turning on Paket on a new solution

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket.VisualStudio#74] opened 2015-09-21 13:00 UTC
What's the "recommended" way of getting a new empty solution e.g. single project class library up and running with Paket in VS?

Currently I do a Convert From Nuget (even though there's no Nuget) which at least generates the dependencies file. But I still have to manually create a .references file in each project etc..

Is there any way to just say "turn on paket for this solution" sort of thing?

**Comment by dcorriveau-omniscient** [comment] 2016-02-03 20:46
Might want to flag this as duplicate of fsprojects/Paket.VisualStudio/issues/85 and close this issue.

**Closed as completed** 2016-02-04 13:55 UTC
